server:
  port: 8092
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_68270deebe07
    token: b9b7
    app-id: wxc6848b5196152b90
    app-secret: c320ca3503428e01c667395c97f8c2a1
    template_id: cLw4M2iNTC50zEUGsVIN-6xTAAnDRi2ehA6C3nqaQZ4

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000141687015
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6yZ11d8ImH2M7siDJNzoQ5V5+WhlVK2RNk5MgHBQjHmaUgNZYOUFUB0QfmHgqfqpBN6tnZl605rBl+Cmbk9tuQMyY+plao6m9ckyoVN3wW2x9dKeq22W5bNzGmiE+YBU/bvh6tyuFY2hdKlnzDaQ9bN6E8kLF4ACC9FjxuQlBlzsyNRmzOYaNBEVTpCsFrDcTDfiPpYMigGtNbP34RLM0GWaloFw/jPVQrbGb/dqFBabu6Y9cZ/dKzic0CqI+VdXw3ZBmloUjXvfuXPxmoYcGYJ72EJLPvtJM2OJVraM3cP6Nc2tQyTUvea6BvimImzfNXv8Emt2ZJeCX/VyQgJdvAgMBAAECggEASKKQTZa1c/eusg8Rus10Eg/vz/ifc0Q9bAFgLBNfLUzsHQGA2KvjIJb2wcabrAK3mEbaq4neeEBhBjYbj/lOUjB2n2KL8fhE0Hu7HZZq+8XBiYOsk79fblzL+ZsEJGpeuN0hWS8TiHpgoiIO+noqjQxh95bxqlryN/pnABCxbcSCWVEg7D75zINRQXT3otmfeax51A3EiXmxzhxhkHXsCCAYVE8J4j2EqJVLxiImBjLvS6kp8Q08MWUQ+/Ok6o+xaoTYT14mg6LLrliK6NubI5c9hSwa9/tRZ+7wnVLs9KrUW0DP2C+cLJ5T3VodmnqFsihFwY3t9RYgIA1kQzfNCQKBgQD+4pUnSiXgQ8jigCrFbtqLs8xW4nhhVc5LNeXB6oVB5txj5P4QBVAzuxN3868MwxhGp33eP1QRHk6431Cm/59mXHgjvmJkXEaBGFagIdMYBfpzI/wH7wf6M4oknf3xvt7cMfD5CS+Ao4IW0iIRg4GeuiAFG9c0C9CqFYnIqOzL0wKBgQC7mscR/RKVlg5Q3h6rF9sopuN+X2GAWhaxv4f2CnAmxsXkHu8UrNaO4CXUKtCa8h/JoFNQ+sWYTDUnTTyPMAAd+JBExAYkhEMh+TDJ2NYRY5nXmSDOYVGvkwVYjOii4Scc+4RDer7g7xE7nZbHyJY/A4kmeJ0YDFzYWERNXyTQdQKBgDBvknSC7Kuvde9E99vI8xL1OfGQ29tzWN6GAYFWNbiOTHdXPsiAmfsao9p5nlxIfsZ+cbbYRftyzPboyQTTMtFa5SG1vjDgMC28GEoZ42l/SVa0EeLYE6YCQVAwDd/wq50giHBqxHInoEMB76NwYCNvr0IJRl4HmMGZkjNllootAoGBAIk9jhnLv/esIWbpRxg0yH+xrsS48/PYc7eufMDyG99SFFxwgMfoNMGqmiHe/GINdFGktq6L9VcXkN7icsXxAHTsbGXR3QiDtTS6PgW7Wca4zUdaXxR7Py2o6QVBd8IH4fwixzwyJEcavMmW3EHkrH0GkiORoqKAEL+3uqe7TYwtAoGAfRK/tOT8sF6jZ7EVYgr+gz5M6/KqLr+43RW9kkT6ty9e93n7OhqIjmmKf0kuNlSoCvDRBCwI3/smHTF9qmczAodkN7GyGAvrhmyHTBZk2blcY811Kq4MxS25hTZyayX5KwFC0s4Dvp0Ecb/JS/ZwwaRkbCAkNtnPX31VEJalmGo=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhfdCpD/4dAcxNU266hRPzQj4+e5YhnYDEIWTrMrg+2xPUHRIcMhrLRejh6hSY+GLLubv7ecOnpHeqpqP2MLLszNtIl9QNtpMpXt8De7b6WB/bVGVwVnxW/yTW1U/sO2Rbzt+c2KMAH1Ptjmc4bElPX3p9ac0s7EGKH9mTIyLDwOc7Vc4AaBR6fovIYtJNLvl3JFpTZKqPrS/iE85h9y7RdwhDM28IwUJ11VWY9C10iIf4mPUcDicznKwqNaz1VV6IFz0YG2U145dwdHrU3ey+57/cEd5fEj8zQDSym1VqYNfp/FJjYhXLJhLXJxNGMjozWINLhZbCeUAjxxgbP5UOQIDAQAB
  notify_url: http://ce84e90.r6.cpolar.top/api/v1/alipay/alipay_notify_url
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    validationQuery: SELECT 1
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    filters: stat

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml